version: '3.8'
services:
  pool-jdbc-rw-postgresql:
    image: docker.io/postgres:10.12
    container_name: pool-jdbc-rw-postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    command: >
      bash -c "
        mkdir -p ${HOME}/pgdata &&
        chmod 700 ${HOME}/pgdata &&
        exec docker-entrypoint.sh postgres
      "
    volumes:
      - "${HOME}/pgdata:/root/pgdata"
      - "${HOME}/pgdata:/var/lib/postgresql/data"
